version: '2.1'

services:
  weatherapp2:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
       DATABASE_Name : myapp
    ports: 
      - 3000:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      db : 
       condition : service_healthy   
  db:
    image: healthcheck/postgres
    environment:
      POSTGRES_USER : root
      POSTGRES_PASSWORD : 123
      POSTGRES_DB : myapp